Add mpv v0.30.0
Buildroot provides mpv v0.29.1. This one fails to build with the
following error message:

[202/202] Linking build/mpv
/nerves/build/host/opt/ext-toolchain/bin/../lib/gcc/arm-unknown-linux-gnueabihf/8.3.0/../../../../arm-unknown-linux-gnueabihf/bin/ld:
video/out/opengl/context_rpi.c.19.o: undefined reference to symbol
'vc_dispmanx_display_close'
/nerves/build/host/opt/ext-toolchain/bin/../lib/gcc/arm-unknown-linux-gnueabihf/8.3.0/../../../../arm-unknown-linux-gnueabihf/bin/ld:
/nerves/build/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libvchostif.so:
error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

This comment creates a new mpv package (called mpv30) that builds
v0.30.0. This version has a fix for the above error.

[DO NOT MERGE - This is for example purposes only]